app/models.py
from app import db, app
from sqlalchemy.dialects.postgresql import ARRAY
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    password_hash = db.Column(db.String(128))

    def __init__(self, **kwargs):
        self.id = kwargs['id']
        self.password = kwargs['password']

    def get_id(self):
        return self.id

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return 'User {}'.format(self.id)

app/forms.py
from flask_wtf import FlaskForm 
from wtforms import StringField, BooleanField, PasswordField, IntegerField, SelectField, DateTimeField, DateField, SelectMultipleField, widgets
from wtforms.validators import DataRequired, Email, Length, Regexp, EqualTo

class LoginForm(FlaskForm):
    id = IntegerField('User ID', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])

class SignUpForm(FlaskForm):
    id = IntegerField('Choose ID (3 Numbers)', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), 
                                                     Length(min=6, message='Password should be at least 6 characters long')])
    password2 = PasswordField('Password Confirmation', validators=[DataRequired(), 
                                                                   Length(min=6, message='Password should be at least 6 characters long'), 
                                                                   EqualTo('password', message="Password must match")])

app/__init__.py
import os
import logging
from logging import Formatter
from logging.handlers import RotatingFileHandler
from flask import Flask
from flask_sqlalchemy import SQLAlchemy 
from flask_login import LoginManager
from flask_sslify import SSLify 

app = Flask(__name__)
app.config.from_object(os.environ['APP_SETTINGS'])
app.config['SQLALCHEMY_TRACK_MODIFICATIONS']=False
app.config['TRAP_HTTP_EXCEPTIONS']=True
db = SQLAlchemy(app)
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.init_app(app)
sslify = SSLify(app)

"""
Logging Files in Flask and in Heroku Server

"""
if app.debug and os.environ.get('HEROKU') is None:
    handler = RotatingFileHandler('error.log', maxBytes=10000, backupCount=1)
    handler.setLevel(logging.INFO)
    handler.setFormatter(Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]'
    ))
    app.logger.addHandler(handler)
    app.logger.setLevel(logging.INFO)

if os.environ.get('HEROKU') is not None:
    stream_handler = logging.StreamHandler()
    app.logger.addHandler(stream_handler)
    app.logger.setLevel(logging.INFO)

"""

Blueprints

"""

from app import models
from app.views import user

app.register_blueprint(user.mod)

app/views/__init__.py
from app import app
from flask import jsonify, render_template

@app.route('/')
@app.route('/index')
def index():
    return render_template('index.html')

"""

Error Handling

"""

@app.errorhandler(500)
def internal_server_error(error):
    responseObject = {
        'status': 'fail',
        'message': 'Try again. 500 Internal Server Error'
    }
    app.logger.error('Server Error: %s',(error))
    return jsonify(responseObject), 200

app/views/user.py
from flask import Blueprint, session, render_template, flash, redirect, url_for, request
from app import login_manager
from flask_login import login_required, logout_user, login_user
from app.forms import LoginForm, SignUpForm
from app.models import User
from app.helpers import save

mod = Blueprint('user', __name__, url_prefix='/user')

login_manager.login_view = 'user.login'

@login_manager.user_loader
def load_user(id):
    return User.query.get(id)

@mod.route('/login', methods=['GET', 'POSt'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.get(form.id.data)
        if user is not None and user.verify_password(form.password.data):
            login_user(user)
            flash('Logged in Successfully')
            return redirect(url_for('user.main'))
        else:
            flash('Invalid id or password')
    return render_template('user/login.html', form=form)

@mod.route('/register', methods=['GET', 'POST'])
def register():
    form = SignUpForm()
    if form.validate_on_submit():
        user = User(id=form.id.data, password=form.password.data)
        if save(user):
            login_user(user)
            flash('Sign Up Successfully')
            return redirect(url_for('user.main'))
        else:
            flash('Try again')
    return render_template('user/register.html', form=form)

@mod.route('/logout', methods=['GET'])
def logout():
    logout_user()
    flash('Log out successfully')
    return redirect(url_for('index'))

@mod.route('/home', methods=['GET'])
@login_required
def main():
    return render_template('index.html')

app/templates/base.html
<!DOCTYPE HTML>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        
        {% block css %}
        <link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">
        {% endblock %}
        
        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

        {% block scripts %}{% endblock %}
  
    </head>
    <body>
    
    <header>
        <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="#">Navbar</a>

          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-md-0">
              <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
              </li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('user.login') }}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('user.register') }}">Sign Up</a></li>  
                {% endif %}

            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>    
    </header>
    
    {% with messages = get_flashed_messages() %}
      {% if messages %}         
        {% for message in messages %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }} 
        </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    
    {% block content %}{% endblock %}
        
    </body>

</html>

app/templates/index.html
{% extends "base.html" %}

{% block title %}
    Index
{% endblock %}

{% block content %}

<div class="jumbotron">
  <h1 class="display-3">Hello, world!</h1>
    {% if current_user.is_authenticated %}
        Welcome {{ current_user.get_id() }}!
    {% else %}
        Sign Up and Register above. 
    {% endif %}

</div>
{% endblock %}

app/templates/macros.html
{% macro render_field(field) %}

  {% if field.errors %}
    <div class="form-group has-error">
      {{ field.label }}
      {{ field(**kwargs)|safe }}
      <span class='help-block'>
        {{ '; '.join(field.errors) }}
      </span>
    </div>
  {% else %}
    <div class="form-group">
      {{ field.label }}
      {{ field(**kwargs)|safe }}
    </div>
  {% endif %}

{% endmacro %}

app/templates/user/login.html
{% extends "base.html" %}
{% from "macros.html" import render_field %}

{% block title %}
    Login
{% endblock %}

{% block content %}
<div class="container">
  <h1>User Log In</h1>
  <form action="{{ url_for('user.login') }}" method="post" name="login">
      {{ form.csrf_token }}
      {{ render_field(form.id, class="form-control", placeholder="ID") }}
      {{ render_field(form.password, class="form-control", placeholder="Password") }}
      <input type="submit" class="btn btn-primary btn-block" value="Login"/>

  </form>
</div>
{% endblock %}

app/templates/user/register.html
{% extends "base.html" %}
{% from "macros.html" import render_field %}

{% block title %}
    Register
{% endblock %}

{% block content %}
<div class="container">
  <h1>User Register</h1>
  <form action="{{ url_for('user.register') }}" method="post" name="register">
      {{ form.csrf_token }}
      {{ render_field(form.id, class="form-control", placeholder="Any Number") }}
      {{ render_field(form.password, class="form-control", placeholder="Password") }}
      {{ render_field(form.password2, class="form-control", placeholder="Type Password again") }}
      <input type="submit" class="btn btn-primary btn-block" value="Login"/>

  </form>
</div>
{% endblock %}